# Dependencies
markdown:         redcarpet
pygments:         true
gems:
  - jekyll-sitemap
# Permalinks
permalink:        pretty

# Setup
title:            Ryan Cheng
tagline:          'Tech & Life'
description:      'Hello,World!'
url:              https://cr1944.github.io
domain:            ShellDone.Com
author:
  name:           'Ryancheng'
  url:            https://github.com/cr1944

paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/shelldonegao/blog