# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ryan Cheng
tagline:          'Tech & Life'
description:      'Hello,World!'
url:              https://cr1944.github.io

author:
  name:           'ShellDone'
  url:            http://weibo.com/shelldone

paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/poole/lanyon
