# Dependencies
markdown:         redcarpet
highlighter:      pygments
#gems:
#  - jekyll-sitemap
# Permalinks
permalink:        pretty

# Setup
excerpt_separator: <!--more-->
title:            Ryan Cheng
tagline:          'Android Develop Blog'
description:      'Hello,World!'
url:              https://cr1944.github.io
domain:            ShellDone.Com
author:
  name:           'Ryancheng'
  url:            https://github.com/cr1944

paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/shelldonegao/blog
